name: Deploy Kerber - Todas as Cidades

on:
  push:
    branches:
      - main
      - porto-alegre
      - viamao

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # ==========================
      # CANOAS
      # ==========================
      - name: Baixar branch Canoas
        uses: actions/checkout@v6
        with:
          ref: main
          path: canoas

      # ==========================
      # PORTO ALEGRE
      # ==========================
      - name: Baixar branch Porto Alegre
        uses: actions/checkout@v6
        with:
          ref: porto-alegre
          path: porto-alegre

      # ==========================
      # VIAMÃO
      # ==========================
      - name: Baixar branch Viamão
        uses: actions/checkout@v6
        with:
          ref: viamao
          path: viamao

      # ==========================
      # MONTAR SITE
      # ==========================
      - name: Montar estrutura do site
        run: |

          mkdir -p public
          mkdir -p public/porto-alegre
          mkdir -p public/viamao

          # CANOAS = MAIN
          rsync -av \
            --exclude='.git' \
            canoas/ \
            public/

          # PORTO ALEGRE
          rsync -av \
            --exclude='.git' \
            porto-alegre/ \
            public/porto-alegre/

          # VIAMÃO
          rsync -av \
            --exclude='.git' \
            viamao/ \
            public/viamao/

          # Impede processamento Jekyll
          touch public/.nojekyll

      # ==========================
      # CONFIGURAR GITHUB PAGES
      # ==========================
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      # ==========================
      # GERAR ARTEFATO
      # ==========================
      - name: Gerar artefato do site
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

  # ==========================
  # DEPLOY
  # ==========================
  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
