name: Deploy Kerber Imóveis

on:
  push:
    branches:
      - main
      - Porto-Alegre
      - Viamao

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # =====================================
      # CANOAS
      # BRANCH: main
      # URL: /8F2K7M9Q/
      # =====================================

      - name: Checkout Canoas
        uses: actions/checkout@v6
        with:
          repository: kerberimoveis/kerberimoveis.github.io
          ref: main
          path: canoas

      # =====================================
      # PORTO ALEGRE
      # BRANCH: Porto Alegre
      # URL: /P4X9A7Z2/
      # =====================================

      - name: Checkout Porto Alegre
        uses: actions/checkout@v6
        with:
          repository: kerberimoveis/kerberimoveis.github.io
          ref: Porto-Alegre
          path: porto-alegre

      # =====================================
      # VIAMÃO
      # BRANCH: Viamao
      # URL: /Q4M8Z2K7/
      # =====================================

      - name: Checkout Viamão
        uses: actions/checkout@v6
        with:
          repository: kerberimoveis/kerberimoveis.github.io
          ref: Viamao
          path: Viamao

      # =====================================
      # MONTAR SITE
      # =====================================

      - name: Montar site
        run: |

          mkdir -p public

          # CANOAS
          mkdir -p public/8F2K7M9Q

          rsync -av \
            --exclude='.git' \
            canoas/ \
            public/8F2K7M9Q/

          # PORTO ALEGRE
          mkdir -p public/P4X9A7Z2

          rsync -av \
            --exclude='.git' \
            porto-alegre/ \
            public/P4X9A7Z2/

          # VIAMÃO
          mkdir -p public/Q4M8Z2K7

          rsync -av \
            --exclude='.git' \
            Viamao/ \
            public/Q4M8Z2K7/

          touch public/.nojekyll

      # =====================================
      # CONFIGURAR GITHUB PAGES
      # =====================================

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      # =====================================
      # UPLOAD
      # =====================================

      - name: Upload do site
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

  # =======================================
  # DEPLOY
  # =======================================

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4
